### ISSUE TITLE
Fix sveltosctl RBAC

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltosctl#151]
I0826 05:47:57.669962     189 main.go:116]  "msg"="classifiers.lib.projectsveltos.io \"default-classifier\" is forbidden: User \"system:serviceaccount:projectsveltos:sveltosctl\" cannot update resource \"classifiers\" in API group \"lib.projectsveltos.io\" at the cluster scope\n"

**Comment by AdamSadek** [comment]
Hi again @gianlucam76  :)

I had a look at this and found that in your k8s manifest file under the RBAC rules, you've only given the _"sveltosctl"_ service account _"get"_ and _"list"_ actions for the api group _"lib.projectsveltos.io"_ (2/3 instances), but not _"update"_ hence why you might be getting _"cannot update resource"_. I think the solution to this would be to add the _"update"_ verb with _"get"_ and _"list"_. If that's the case, I'm happy to help :)

Thanks
Adam

**Comment by gianlucam76** [comment]
Hi @AdamSadek thank you. Yes what you are suggesting would fix this issue. 

I would love to get your help. If you don't mind pushing a fix, branch is "dev" as we use "dev" for development and sync to main (which we keep stable) only after a new release.

Thank you so much again!!!
