### ISSUE TITLE
BUG: Release v0.28.0 linux-amd64 contains old client version v0.27.0-17

### ISSUE THREAD

**Issue by egrosdou01** [projectsveltos/sveltosctl#236]
# Problem Description

Latest release v0.28.0 linux-amd64 contains old the client version v0.27.0-17.

``
$ curl -L -o sveltosctl https://github.com/projectsveltos/sveltosctl/releases/download/v0.28.0/sveltosctl-linux-amd64

$ sveltosctl version
I0428 09:05:01.496691 2181388 version.go:64] "Client Version:   v0.27.0-17-2fb25f7e7a15a3"
I0428 09:05:01.496715 2181388 version.go:65] "Git commit:       2fb25f7e7a15a3adc351e569f79ec1f80ae1ac7e"
``

# Logs

``
$ sveltosctl generate --help
Usage:
        sveltosctl generate <command> [<args>...]

        kubeconfig    Generates a Kubeconfig. The generated Kubeconfig can then be used to register a cluster.
                      Run this command while pointing to the managed cluster.

Options:
        -h --help      Show this screen.

Description:
        See 'sveltosctl generate kubeconfig --help' to read about a specific subcommand.
``

**Comment by gianlucam76** [comment]
Fixed it.

I had built and uploaded the binaries before creating the new release. So the incorrect release information.

Re-built all binaries and uploaded all again.
