### ISSUE TITLE
Add Feedback for Cluster Registrations

### ISSUE THREAD

**Issue by emreberber** [projectsveltos/sveltosctl#303]
#### Description
When using the `sveltosctl register cluster` command, no feedback is provided for successful operations or when the cluster is already registered. While error messages are displayed if something goes wrong, users receive no confirmation for success or pre-existing registrations. This can create confusion and lead to unnecessary manual verification.

For example, after running:

```
sveltosctl register cluster \
    --namespace=dev \
    --cluster=dev-01 \
    --kubeconfig=./dev-01.yml \
    --labels=environment=dev,name=dev-01
``` 

If the registration is successful or the cluster is already registered, the CLI remains silent.

#### Proposed Solution
Add simple, default feedback for successful and already-registered scenarios:

**1. Success:**

```
Cluster 'dev-01' successfully registered in namespace 'dev'.
``` 

**2. Already Registered:**

```
Cluster 'dev-01' is already registered in namespace 'dev'.
```

These messages improve user experience without requiring **verbose** mode.

#### Benefits
- **Clarity**: Users get immediate confirmation of their actions.
- **Usability**: Eliminates the need for manual checks post-command.
- **Consistency**: Aligns with standard CLI behavior for feedback.

**Comment by gianlucam76** [comment]
Same message will be printed in case cluster is successfully registered for the first time or updated. 

```
sveltosctl register cluster --namespace=civo --cluster=cluster2 --kubeconfig=/Users/mgianluc/Downloads/civo-cluster2-kubeconfig  --labels=env=production
cluster cluster2 successfully registered/updated in namespace civo.
```
