### ISSUE TITLE
docker images

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltosctl#52]
Currently for sveltosctl (and all other sveltos microservices) all docker images are stored in docker-hub under namespace gianlucam76. Replace this to use namespace projectsveltos.

**Comment by AdamSadek** [comment]
Hi Gianluca, 

I presume it's just a case of changing the REGISTRY variable in the "Makefile" script from _gianlucam76_ to _projectsveltos_ ?

Happy to make the change in a PR if that is the case.

Thanks

**Comment by gianlucam76** [comment]
Hi @AdamSadek thank you so much. Yes essentially in sveltosctl repo:

1. Change REGISTRY in Makefile as you described above
2. sveltosctl is different from other sveltos repos (it is not a controller, just a pure CLI mostly) so manifest does not get regenerate currently. Which means also changing registry in manifest/sveltosctl.yaml

Just FYI, other sveltos repos the change is simpler. For instance in drift-detection-manager 
1. Change REGISTRY in Makefile as you described 
2. make generate
3. make manifest

Thanks again for helping with sveltoctl.

**Comment by AdamSadek** [comment]
Hi @gianlucam76 

My pleasure! I see yes, that's correct. Will create the PR soon. Which branch are you currently working on?

**Comment by gianlucam76** [comment]
Thank you.

Please use _dev_ branch.

**Comment by gianlucam76** [comment]
Resolved by this [PR](https://github.com/projectsveltos/sveltosctl/commit/1fa828a69b2094a4131ce2eb961ff4edda3a3218) by @AdamSadek  (thank you again)
